from __future__ import annotations

# Known model versions per provider — refreshed July 2026
PROVIDER_MODELS: dict[str, list[dict]] = {
    "anthropic": [
        {"id": "claude-fable-5",              "label": "Claude Fable 5",          "tier": "flagship"},
        {"id": "claude-opus-4-8",             "label": "Claude Opus 4.8",         "tier": "flagship"},
        {"id": "claude-sonnet-5",             "label": "Claude Sonnet 5",         "tier": "standard"},
        {"id": "claude-sonnet-4-6",           "label": "Claude Sonnet 4.6",       "tier": "standard"},
        {"id": "claude-haiku-4-5-20251001",   "label": "Claude Haiku 4.5",        "tier": "fast"},
        {"id": "claude-3-5-sonnet-20241022",  "label": "Claude 3.5 Sonnet",       "tier": "standard"},
        {"id": "claude-3-5-haiku-20241022",   "label": "Claude 3.5 Haiku",        "tier": "fast"},
        {"id": "claude-opus-4-7",             "label": "Claude Opus 4.7",         "tier": "flagship"},
        {"id": "claude-3-opus-20240229",      "label": "Claude 3 Opus",           "tier": "flagship"},
    ],
    "openai": [
        {"id": "gpt-5.6-sol",     "label": "GPT-5.6 Sol",     "tier": "flagship"},
        {"id": "gpt-5.6-terra",   "label": "GPT-5.6 Terra",   "tier": "standard"},
        {"id": "gpt-5.6-luna",    "label": "GPT-5.6 Luna",    "tier": "fast"},
        {"id": "o3",              "label": "o3",               "tier": "reasoning"},
        {"id": "gpt-4.1",         "label": "GPT-4.1",         "tier": "standard"},
        {"id": "gpt-4.1-mini",    "label": "GPT-4.1 Mini",    "tier": "fast"},
        {"id": "gpt-4o",          "label": "GPT-4o",          "tier": "standard"},
        {"id": "gpt-4o-mini",     "label": "GPT-4o Mini",     "tier": "fast"},
    ],
    "deepseek": [
        {"id": "deepseek-v4-pro",   "label": "DeepSeek V4 Pro",   "tier": "flagship"},
        {"id": "deepseek-v4-flash", "label": "DeepSeek V4 Flash", "tier": "fast"},
    ],
    "moonshot": [
        {"id": "kimi-k3",                     "label": "Kimi K3 (1M ctx)",         "tier": "flagship"},
        {"id": "kimi-k2.7-code",              "label": "Kimi K2.7 Code",           "tier": "code"},
        {"id": "kimi-k2.7-code-highspeed",    "label": "Kimi K2.7 Code Highspeed", "tier": "code"},
        {"id": "kimi-k2.6",                   "label": "Kimi K2.6",                "tier": "standard"},
    ],
    "glm": [
        {"id": "glm-4.5",       "label": "GLM-4.5",        "tier": "flagship"},
        {"id": "glm-4.5-air",   "label": "GLM-4.5 Air",    "tier": "standard"},
        {"id": "glm-4.5-x",     "label": "GLM-4.5-X",      "tier": "fast"},
        {"id": "glm-4.5-airx",  "label": "GLM-4.5 AirX",   "tier": "fast"},
        {"id": "glm-4.5-flash", "label": "GLM-4.5 Flash",  "tier": "fast"},
        {"id": "glm-4",         "label": "GLM-4 (legacy)",  "tier": "standard"},
    ],
    "minimax": [
        {"id": "MiniMax-M3",               "label": "MiniMax M3 (1M ctx)",       "tier": "flagship"},
        {"id": "MiniMax-M2.7",             "label": "MiniMax M2.7",              "tier": "standard"},
        {"id": "MiniMax-M2.7-highspeed",   "label": "MiniMax M2.7 Highspeed",    "tier": "fast"},
        {"id": "MiniMax-M2.5",             "label": "MiniMax M2.5",              "tier": "standard"},
        {"id": "MiniMax-M2.5-highspeed",   "label": "MiniMax M2.5 Highspeed",    "tier": "fast"},
        {"id": "MiniMax-M2.1",             "label": "MiniMax M2.1",              "tier": "standard"},
        {"id": "MiniMax-M2.1-highspeed",   "label": "MiniMax M2.1 Highspeed",    "tier": "fast"},
    ],
    "mistral": [
        {"id": "mistral-large-latest",    "label": "Mistral Large 3",     "tier": "flagship"},
        {"id": "mistral-medium-latest",   "label": "Mistral Medium 3.5",  "tier": "standard"},
        {"id": "mistral-small-latest",    "label": "Mistral Small 4",     "tier": "fast"},
        {"id": "ministral-8b-latest",     "label": "Ministral 8B",        "tier": "fast"},
        {"id": "devstral-medium-latest",  "label": "Devstral 2",          "tier": "code"},
        {"id": "codestral-latest",        "label": "Codestral",           "tier": "code"},
    ],
    "google": [
        {"id": "gemini-3.6-flash",       "label": "Gemini 3.6 Flash",      "tier": "standard"},
        {"id": "gemini-3.5-flash",       "label": "Gemini 3.5 Flash",      "tier": "fast"},
        {"id": "gemini-3.5-flash-lite",  "label": "Gemini 3.5 Flash-Lite", "tier": "fast"},
        {"id": "gemini-2.5-pro",         "label": "Gemini 2.5 Pro",        "tier": "flagship"},
        {"id": "gemini-2.5-flash",       "label": "Gemini 2.5 Flash",      "tier": "fast"},
        {"id": "gemini-2.5-flash-lite",  "label": "Gemini 2.5 Flash-Lite", "tier": "fast"},
    ],
    "azure_openai": [
        {"id": "gpt-5",          "label": "GPT-5 (Azure)",       "tier": "flagship"},
        {"id": "gpt-5-mini",     "label": "GPT-5 Mini (Azure)",  "tier": "standard"},
        {"id": "gpt-5-nano",     "label": "GPT-5 Nano (Azure)",  "tier": "fast"},
        {"id": "gpt-4.1",        "label": "GPT-4.1 (Azure)",     "tier": "standard"},
        {"id": "gpt-4.1-mini",   "label": "GPT-4.1 Mini (Azure)","tier": "fast"},
        {"id": "gpt-4o",         "label": "GPT-4o (Azure)",      "tier": "standard"},
        {"id": "gpt-4o-mini",    "label": "GPT-4o Mini (Azure)", "tier": "fast"},
        {"id": "DeepSeek-V3.2",  "label": "DeepSeek V3.2",       "tier": "standard"},
        {"id": "DeepSeek-R1-0528","label": "DeepSeek R1",        "tier": "reasoning"},
        {"id": "grok-4",         "label": "Grok 4",              "tier": "flagship"},
        {"id": "grok-3-mini",    "label": "Grok 3 Mini",         "tier": "fast"},
    ],
    "ollama": [
        {"id": "llama3.3:70b",          "label": "Llama 3.3 70B",        "tier": "flagship"},
        {"id": "qwen2.5:32b",           "label": "Qwen 2.5 32B",         "tier": "standard"},
        {"id": "qwen3.6:27b",           "label": "Qwen 3.6 27B",         "tier": "standard"},
        {"id": "llama3.1:8b",           "label": "Llama 3.1 8B",         "tier": "fast"},
        {"id": "llama3.2",              "label": "Llama 3.2 3B",         "tier": "fast"},
        {"id": "qwen2.5-coder:32b",     "label": "Qwen 2.5 Coder 32B",   "tier": "code"},
        {"id": "qwen2.5-coder:7b",      "label": "Qwen 2.5 Coder 7B",    "tier": "code"},
        {"id": "qwen3-coder:30b",       "label": "Qwen3 Coder 30B",      "tier": "code"},
        {"id": "devstral:24b",          "label": "Devstral 24B",          "tier": "code"},
        {"id": "deepseek-r1:32b",       "label": "DeepSeek R1 32B",       "tier": "reasoning"},
        {"id": "deepseek-r1:14b",       "label": "DeepSeek R1 14B",       "tier": "reasoning"},
        {"id": "deepseek-r1:7b",        "label": "DeepSeek R1 7B",        "tier": "reasoning"},
        {"id": "gpt-oss:20b",           "label": "GPT-OSS 20B",           "tier": "reasoning"},
        {"id": "gpt-oss:120b",          "label": "GPT-OSS 120B",          "tier": "flagship"},
        {"id": "phi4-mini",             "label": "Phi-4 Mini 3.8B",       "tier": "fast"},
        {"id": "gemma2",                "label": "Gemma 2",               "tier": "fast"},
        {"id": "mistral",               "label": "Mistral 7B",            "tier": "fast"},
        {"id": "nomic-embed-text",      "label": "Nomic Embed Text",      "tier": "embeddings"},
    ],
}

TIER_COLORS = {
    "flagship":   {"bg": "rgba(124,58,237,0.12)", "border": "rgba(124,58,237,0.3)", "color": "#a78bfa"},
    "standard":   {"bg": "rgba(0,212,255,0.08)",  "border": "rgba(0,212,255,0.2)",  "color": "#00d4ff"},
    "fast":       {"bg": "rgba(74,222,128,0.08)", "border": "rgba(74,222,128,0.2)", "color": "#4ade80"},
    "reasoning":  {"bg": "rgba(251,146,60,0.08)", "border": "rgba(251,146,60,0.2)", "color": "#fb923c"},
    "code":       {"bg": "rgba(251,191,36,0.08)", "border": "rgba(251,191,36,0.2)", "color": "#fbbf24"},
    "embeddings": {"bg": "rgba(156,163,175,0.08)","border": "rgba(156,163,175,0.2)","color": "#9ca3af"},
}
